# Generated by Django 3.2 on 2021-04-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geolocation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='holiday_signup',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
