# Generated by Django 3.2 on 2021-04-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210423_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='holiday_signup',
        ),
        migrations.AddField(
            model_name='user',
            name='signup_holiday',
            field=models.TextField(blank=True, null=True),
        ),
    ]
